name: Generate sponsors.svg
on:
  schedule: [{ cron: '0 2 * * 1' }]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.PAT }}
          SPONSORKIT_GITHUB_LOGIN: loro-dev
      - name: Commit SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sponsors.*
          git commit -m "chore: update sponsors.svg" || echo "no changes"
          git push
